### PR TITLE
Fix QTH locator regex, use re.fullmatch

### PR DESCRIPTION
**Pull request by oddstr13**
First locator group is A-R, `RR-AR` border being the international date line in the arctic ocean/north pole, and `AR-AA` being the international date line on the south pole.

I'm also inclined to add a special case for returning False when the locator is `RR73`, which technically is a valid locator, but is unlikely to actually be used in that context due to it's location.
What is your opinion on this?

### CODE REVIEW

**Comment by schlatterbeck** [comment]
Merged, thanks!
Good idea to use fullmatch here.

**Comment by oddstr13** [comment]
Yea, my script crashed because I feed maidenhead a (non-standard) callsign that matched a four letter locator at the start, but was 7 letters :sweat_smile:

**Comment by schlatterbeck** [comment]
On Sun, Oct 22, 2023 at 04:37:50AM -0700, Odd Stråbø wrote:
> Yea, my script crashed because I feed maidenhead a (non-standard)
> callsign that matched a four letter locator at the start, but was 7
> letters :sweat_smile: 

Ouch .-)
And I think there are some modes that use a longer locator, not to
mention special contest wsjtx telegrams that use a 6-char locator.
I'm using
<OE3RSU/3> <OE3RSU/3> 597373 JN87BV
to give my locator when I'm in Lindabrunn (a small town in lower
Austria). This (mis-)uses a standard wsjtx contest telegram. So I'm able
to give my locator to anyone listening when using a non-standard
callsign where no locator is transmitted with wsjtx.
I had discussed this with Bill Somerville, G4WJS, before he went sk...
you can simply put that (long) message into a macro and transmit it when
needed.

Thanks!
Ralf
-- 
Dr. Ralf Schlatterbeck                  Tel:   +43/2243/26465-16
Open Source Consulting                  www:   www.runtux.com
Reichergasse 131, A-3411 Weidling       email: ***@***.***

**Comment by oddstr13** [comment]
I am already expecting and testing for longer locator formats, [`maidenhead`](https://pypi.org/project/maidenhead/) handles up to [«extended square»](https://en.wikipedia.org/wiki/Maidenhead_Locator_System#Description_of_the_system) (8 character) locators.

https://github.com/oddstr13/wsjtx-influxdb/blob/5ba760ad2c9186687883f0edfc22894700c77a13/tests/test_utils.py#L69-L89

I see that I need to add some tests for 4 character locators to my decimal degrees conversion test.

The reason it failed was because I was feeding the callsign [PF01MAX](https://www.qrz.com/db/PF01MAX) into `maidenhead` as if it was a locator, because `is_locator()` treated it as such :sweat_smile:
(Exact message was `CQ NA PF01MAX`, I hadn't yet special cased `NA` as I do `DX`)

This lead to me being greeted with a very sad looking Grafana dashboard this morning.
image

No data lost tho, I just need to reprocess the WSJT-X logfile, but I want to add multithreading support first, such that I can receive live events while processing the backlog, instead of losing 5min while processing.

**Comment by schlatterbeck** [comment]
On Sun, Oct 22, 2023 at 05:13:17AM -0700, Odd Stråbø wrote:
> I am already expecting and testing for longer locator formats,
> [`maidenhead`](https://pypi.org/project/maidenhead/) handles up to
> [«extended
> square»](https://en.wikipedia.org/wiki/Maidenhead_Locator_System#Description_of_the_system)
> (8 character) locators.

Yes, I noticed this during merging, sorry if I wasn't clear on this.

> I see that I need to add some tests for 4 character locators to my
> decimal degrees conversion test.
> 
> (Exact message was `CQ NA PF01MAX`, I hadn't yet special cased `NA` as
> I do `DX`)

Hmm, there are many two-character extensions to CQ, so maybe you should
allow any middle two-character thing before the callsign.

73 Ralf
-- 
Dr. Ralf Schlatterbeck                  Tel:   +43/2243/26465-16
Open Source Consulting                  www:   www.runtux.com
Reichergasse 131, A-3411 Weidling       email: ***@***.***

**Comment by oddstr13** [comment]
> Hmm, there are many two-character extensions to CQ, so maybe you should allow any middle two-character thing before the callsign.

That sounds like a good idea. I'm not familiar with all the shorthands used in HAM, and searching doesn't often produce good results – I was trying to find a proper definition of RR73, but got nothing useful from my searches, other than the fact that [73 stems from the «Western Union 92 code»](https://hamradioprep.com/what-does-73-mean/), and that RR is short for RRR, essentially two messages condensed into one. Presumably, RRR means something like «received», gleaned from the context it seems to be used.

The [Wikipedia article on CQ](https://en.wikipedia.org/wiki/CQ_(call)#History_and_usage) gives me some good context for what to expect after `CQ` tho, so thanks for the pointer there :smiley:

**Comment by schlatterbeck** [comment]
On Sun, Oct 22, 2023 at 06:55:24AM -0700, Odd Stråbø wrote:
> > Hmm, there are many two-character extensions to CQ, so maybe you should allow any middle two-character thing before the callsign.
> 
> That sounds like a good idea. I'm not familiar with all the shorthands
> used in HAM, and searching doesn't often produce good results – I was
> trying to find a proper definition of RR73, but got nothing useful
> from my searches, other than the fact that [73 stems from the «Western
> Union 92 code»](https://hamradioprep.com/what-does-73-mean/), and that
> RR is short for RRR, essentially two messages condensed into one.
> Presumably, RRR means something like «received», gleaned from the
> context it seems to be used.

Yes, the RR/RRR stuff is wsjtx specific, not ham radio. And 73 has a
good definition in wikipedia
https://en.wikipedia.org/wiki/73_(number)
"Amateur radio operators and other morse code users commonly use the
number 73 as a "92 Code" abbreviation for "best regards", typically when
ending a QSO"
It has a specific sound in morse-code: dah-dah-dit-dit-dit
dit-dit-dit-dah-dah :-)

> The [Wikipedia article on
> CQ](https://en.wikipedia.org/wiki/CQ_(call)#History_and_usage) gives
> me some good context for what to expect after `CQ` tho, so thanks for
> the pointer there :smiley: 

CQ originally stands for 'seek you' (from the sound when spelling it in
english) and is a call to everybody willing to answer. Interesting that
the wikipedia article doesn't seem to mention the spelling thing.

73 Ralf
-- 
Dr. Ralf Schlatterbeck                  Tel:   +43/2243/26465-16
Open Source Consulting                  www:   www.runtux.com
Reichergasse 131, A-3411 Weidling       email: ***@***.***

**Pull request merged**
